language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install --upgrade pip
    - pip install jinja2 mistune
script: ./test.sh
after_success:
    - coveralls
branches:
    only:
        - master
sudo: false
